server:
  port: 8021
#  ssl:
#    enabled: false
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    # 虚拟host 可以不设置,使用server默认host
    virtual-host: canHost
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已经发送到队列(Queue)
    publisher-returns: true
    listener:
      type: simple
      # 消费方消息确认：手动确认
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false