#minio:endpoint: http://localhost:9001
#  accessKey: root
  # secretKey: root1234
  # bucketName: weiz-test
spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB

#  endpoint: http://localhost:9001
#  accessKey: miniouser
#  secretKey: miniouser
#  bucketName: public
minio:
  endpoint: http://localhost:9000
  accessKey: Y99fRLda4hS1Dd7X
  secretKey: O4KJPCEj2OC7vRdlp5bwphaQjtIegX1E
  bucketName: public
